# description
name: "dyspoezja"
description: "Niewiersze"
keywords: ""
author: "Leszek Pietrzak"
email: "smutnyleszek@gmail.com"
language: "pl-PL"

# address settings
rootSiteUrl: "http://smutnyleszek.com"
baseurl: "http://dyspoezja.smutnyleszek.com"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw
# 0 to 65535
port: 2038

exclude:
    - node_modules
    - LICENSE
    - README.md
    - package.json
    - package-lock.json

# ------------------------------------------------------------------------------
# page categories and custom collections
# ------------------------------------------------------------------------------

collections:
    niewiersze:
        output: true
        permalink: /:collection/:name/index.html
defaults:
    - scope:
        path: ''
        type: niewiersze
      values:
        layout: poem
